# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('next_menu_id', models.IntegerField()),
                ('step', models.IntegerField()),
                ('confirmation_phrase', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('has_precondition', models.IntegerField()),
                ('type', models.IntegerField()),
                ('is_parent', models.BooleanField()),
                ('confirmation_message', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('menu_id', models.IntegerField()),
                ('menu_item_id', models.IntegerField()),
                ('response', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('session', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('confirm_from', models.IntegerField()),
                ('menu_id', models.IntegerField()),
                ('menu_item_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='ussd.Menus'),
        ),
    ]
