# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_remove_menuitems_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='confirm_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='menu_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='menu_item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
