# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_auto_20160220_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='confirmation_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='is_parent',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='menus',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
