# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_auto_20160220_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_registration_done',
            field=models.IntegerField(default=0),
        ),
    ]
