# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_users_is_registration_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='response',
            new_name='user_input',
        ),
    ]
